### ISSUE TITLE
Text styles are being overridden on the front end.

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/mememe#2]
When I create a meme it looks great in the backend but not on the front. The theme styles are messing it up. We need to find a way to prevent this.

<img width="736" alt="Screen Shot 2020-01-15 at 10 32 10 AM" src="https://user-images.githubusercontent.com/158918/72452050-82536100-3782-11ea-8a0a-fe451651a7ea.png">
<img width="1076" alt="Screen Shot 2020-01-15 at 10 32 17 AM" src="https://user-images.githubusercontent.com/158918/72452051-82ebf780-3782-11ea-9032-187a1e1538b1.png">

**Comment by ajitbohra** [comment]
Fixed in 79241fdce330f5fb4ae8a7ed3646fc81a578d7b9
