### ISSUE TITLE
Apply styles on the backend

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/mememe#4]
Can we make the caption appear the exact same on the backend as it does on the front? Currently when you change any settings it's not reflected on the backend. I think this would be helpful for people to see and understand how it is going to look.

**Comment by nickhamze** [comment]
I added a fresh block on a fresh page and this is all I see. The size and position doesn't chance when I change the settings. This is just in the editor, everything else works fine. 

<img width="776" alt="Screen Shot 2020-01-21 at 8 26 54 AM" src="https://user-images.githubusercontent.com/158918/72812895-f8931000-3c27-11ea-97c1-fedbbecdfc3d.png">

**Comment by ajitbohra** [comment]
Unable to replicate
