### ISSUE TITLE
Meme caption style applied all the time

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/mememe#5]
I think this line of CSS (and related ones) are causing some trouble:
wp-block-image.has-meme-position-top figcaption {
}

Even when the meme style isn't active the CSS is still being applied to the captions.

**Comment by ajitbohra** [comment]
Unable to replicate

**Comment by nickhamze** [comment]
Sorry I should have given more detail. 

Steps to reproduce.

Here is what our image looks like with the meme style applied. Everything looks like it should.
<img width="819" alt="Screen Shot 2020-01-24 at 5 21 30 AM" src="https://user-images.githubusercontent.com/158918/73065609-932e6180-3e69-11ea-8a85-e12cd097dabb.png">

Here is what happens when we apply the default style. The caption is all the way in the corner:
<img width="1210" alt="Screen Shot 2020-01-24 at 5 23 04 AM" src="https://user-images.githubusercontent.com/158918/73065655-b527e400-3e69-11ea-931c-3af0e487d779.png">

It's doing that because this line of CSS is being applied but it really shouldn't be as the style isn't active:
<img width="1439" alt="Screen Shot 2020-01-24 at 5 24 04 AM" src="https://user-images.githubusercontent.com/158918/73065709-d7216680-3e69-11ea-89e3-40e9f2051eb0.png">

I think it could be fixed by changing by adding the ".is-style-meme" class to all the caption related css. Like this:

```
.wp-block-image.is-style-meme.has-meme-position-top figcaption
{
position:absolute;top:5%;left:0;right:0
}

wp-block-image.is-style-meme.has-meme-position-bottom figcaption
{
position:absolute;bottom:5%;left:0;right:0
}
```
